name=input("enter your name")
city=input("enter city")
age=input("enter age")
print=("name is" + (name) + "age is" + (age) + "years oold" + " city is" + (city))
print=("name is {name} and age is {age} and city is {city}")
